### ISSUE TITLE
Account last match calls a random match in dotabuff

### ISSUE THREAD

**Issue by crlsgms** [nickgermyn/node-dogte-chat#50]
Hello everyone, I dont know if you just created the code, or you maintain the @dogtebot bot alive yourselfs. I'v setup the bot on our group chat, and created my account with my steam id and dotabuff id:
/register@dogtebot steam:crlsgms dotabuff:85895827

the display results are: 
{
 "_id": "5812229bf1df941f0aff6271",
 "telegramId": "22026886",
 "userName": "crlsgms",
 "displayName": "Carlos Gomes",
 "__v": 0,
 "dotaBuffId": "85895827"
}

But the last match call, gives me some odd matchs, such as:
http://www.dotabuff.com/matches/2738267062

Did I miss something?

**Comment by nickgermyn** [comment]
When you register, you need to use your steamID64, not your user name. You can lookup this information on sites such as https://steamid.io/
Currently the dotabuff ID is not used, it was added for future expansion possibility.
